spring:
    kafka:
        bootstrap-servers: localhost:9092

app:
    kafka:
        topics:
            orderTopic: "order-topic"
            orderStatusTopic: "order-status-topic"
        groups:
            orderStatusGroupId: "order-status-group"