server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topics:
      orderTopic: "order-topic"
      orderStatusTopic: "order-status-topic"
    groups:
      orderEventGroupId: "order-event-group"
